[project]
name = "crewai-multiagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel",
	"crewai",
	"crewai_tools",
	"python-dotenv"
]
